apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}-api
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "taskmanager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api