apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}-frontend
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "taskmanager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend