{{- if (index .Values "mongo-express").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}-mongo-express
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongo-express
spec:
  type: {{ (index .Values "mongo-express").service.type }}
  ports:
    - name: http
      port: {{ (index .Values "mongo-express").service.port }}
      targetPort: http
      {{- if and (eq (index .Values "mongo-express").service.type "NodePort") (index .Values "mongo-express").service.nodePort }}
      nodePort: {{ (index .Values "mongo-express").service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongo-express
{{- end }}