apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmanager.fullname" . }}-mongodb
  labels:
    {{- include "taskmanager.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "taskmanager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb