apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  mongo-user: {{ .Values.secrets.mongoUser | b64enc | quote }}
  mongo-password: {{ .Values.secrets.mongoPassword | b64enc | quote }}
  express-user: {{ .Values.secrets.expressUser | b64enc | quote }}
  express-password: {{ .Values.secrets.expressPassword | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}