services:
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    # Healthcheck configuration
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
