services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # API service (Node/Express)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    volumes:
      - .:/app # Mount the current 'backend' folder to app
      - ./wait-for-it.sh:/app/wait-for-it.sh # mount the script explicitly
    command: ["./wait-for-it.sh", "mongodb", "27017", "--", "npm", "run", "dev"]

volumes:
  mongodb_data:
