version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: task-manager
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI='mongodb://mongodb:27017/task-manager'
      - JWT_SECRET='your-secret-key' # hardcoded for development only
    volumes:
      - .:/user/src/app # Mount the current 'backend' folder to app

volumes:
  mongodb_data:
