apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        service: api
    spec:
      containers:
        - image: docker.io/armartini/taskmanager-api:v1
          imagePullPolicy: Always
          name: taskmanager-api
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: jwt-secret
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: mongo-password
            - name: MONGO_URI
              value: mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo:27017/task-manager?authSource=admin
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
