apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    service: frontend
