apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
      nodePort: 30100
  selector:
    service: frontend
