apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        service: frontend
    spec:
      containers:
        - image: taskmanager-frontend
          imagePullPolicy: IfNotPresent
          name: taskmanager-frontend
          ports:
            - containerPort: 5173
              protocol: TCP
      restartPolicy: Always
