apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo-express
  template:
    metadata:
      labels:
        service: mongo-express
    spec:
      containers:
        - env:
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: express-user
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: express-password
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: mongo-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secrets
                  key: mongo-password
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: admin
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
          image: mongo-express
          name: taskmanager-mongo-express
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
