apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongo-express
  name: mongo-express
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30101
  selector:
    service: mongo-express
