apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo-express
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        service: mongo-express
    spec:
      containers:
        - env:
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: myexpresspass
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: myexpressuser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: secret
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: admin
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
          image: mongo-express
          name: taskmanager-mongo-express
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
