apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secrets
type: Opaque
data:
  mongo-user: YWRtaW4=
  mongo-password: c2VjcmV0
  express-user: bXlleHByZXNzdXNlcg==
  express-password: bXlleHByZXNzcGFzcw==
  jwt-secret: YS1tdWNoLWJldHRlci1zZWNyZXQtdGhhdC1pcy1ub3QtaW4tZ2l0
